# Generated by Django 4.2.4 on 2023-08-20 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emp',
        ),
    ]
